# Generated by Django 3.1.4 on 2021-01-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zvo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pw',
            new_name='pw_hash',
        ),
    ]
