# Generated by Django 3.1.4 on 2021-01-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvo_app', '0002_auto_20210104_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
