# Generated by Django 3.1.5 on 2021-02-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvo_app', '0005_auto_20210202_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='file',
            field=models.FileField(upload_to='demos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
