# Generated by Django 3.1.5 on 2021-02-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvo_app', '0006_auto_20210202_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='pic',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
