# Generated by Django 3.1.5 on 2021-02-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvo_app', '0007_about_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='pic',
            field=models.FileField(upload_to='pics/'),
        ),
    ]
