# Generated by Django 3.1.5 on 2021-02-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvo_app', '0010_auto_20210215_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='backup_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
