# Generated by Django 3.1.5 on 2021-02-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvo_app', '0011_video_backup_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='header',
            field=models.TextField(default='Greetings, denizen!'),
            preserve_default=False,
        ),
    ]
